- name: Tower Team Users Role Playbook
  hosts: localhost
  gather_facts: no
  #vars_files:
  #- vars_users.yml

  tasks:
  #- name: Run Lab script
  #  import_tasks: lab_script.yml

  - name: Add tower inventory
    tower_inventory:
      name: "Dev"
      description: "Development Inventory"
      organization: "Default"
      state: "present"
      tower_host: "tower.lab.example.com"
      tower_username: "admin"
      tower_password: "redhat"
      validate_certs: false

  - name: Add Inventory via command Line
    shell: >
            tower-cli inventory create
            --name "Dev" --organization "Default" 
            --description "Development Inventory"
            --tower-host "tower.lab.example.com" --tower-username "admin"
            --tower-password "redhat" --insecure
            

  - name: Add tower group's
    tower_group:
      name: "dev-servers"
      description: "Development servers"
      inventory: "Dev"
      state: "present"
      tower_config_file: "{{ tower_credential_file }}"
    register: inventory_groups_output

####  Print Group information created earlier, as it will be
####  used later
 
  - name: Print group's information
    debug:
      var: inventory_groups_output
   
  - name: Add tower host with "admin" user rights
    tower_host:
      name: "{{ item.server_name }}"
      description: "{{ item.server_description }}"
      inventory: "Dev"
      tower_host: "tower.lab.example.com"
      tower_username: "admin"
      tower_password: "redhat"
      validate_certs: false
      state: "present"
    loop:
    - server_name: "servera.lab.example.com"
      server_description: "Server A"
    - server_name: "serverb.lab.example.com"
      server_description: "Server B"
    register: inventory_hosts_output

  - name: Print Hosts Information
    debug:
      var: inventory_hosts_output
      
  - name: Associate 'servere.lab.example.com' Host to Group 'prod-servers'
    shell: > 
            tower-cli host associate  
            --host "{{ item.id }}" 
            --group "{{ inventory_groups_output.id }}" 
            --tower-host "tower.lab.example.com" --tower-username "admin" 
            --tower-password "redhat" --insecure
    loop: "{{ inventory_hosts_output.results }}"




  - name: Add admin role to Developers team via tower_role
    tower_role:
      inventory: "Dev"
      team: "Developers"
      role: "admin"
      state: "present"
      tower_host: "tower.lab.example.com"
      tower_username: "admin"
      tower_password: "redhat"
      validate_certs: false

  - name: Add credential "Developers"
    tower_credential:
      name: "Developers"
      description: "Developers Credential"
      organization: "Default"
      username: "devops"
      password: "redhat"
      become_method: "sudo"
      become_username: "root"
      become_password: "redhat"
      kind: "ssh"
      state: "present"
      tower_config_file: "{{ tower_credential_file }}"

  - name: Add admin role to Developers team via tower_role
    tower_role:
      credential: "Developers"
      team: "Developers"
      role: "admin"
      state: "present"
      tower_config_file: "{{ tower_credential_file }}"
