- name: This is my First Playbook
  hosts: servera*
  gather_facts: false
  remote_user: devops
  tasks:
    # sdfsdfv
    - name: Create a new DIR in /tmp dir
      ansible.builtin.file:
        path: /tmp/mydir
        state: directory
        mode: 0755

    - name: create a file in above dir
      ansible.builtin.copy:
        content: "SOmething here AGAIn"
        dest: /tmp/mydir/bla.txt
        mode: 0644

    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present
