- name: Install Multiple packages/services
  hosts: servera*
  become: true
  tasks:
    - name: Install Many packages
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
          - httpd-tools
          - mariadb-server
          - mariadb
          - php
          - php-mysqlnd
        state: present
    
    - name: Start many service loop as no other option
      service:
        name: "{{ item }}"
        state: started
      loop:
          - httpd
          - mariadb
    # - name: Install Many packages
    #   ansible.builtin.dnf:
    #     name: "{{ item }}"
    #   loop:
    #       - httpd
    #       - mod_ssl
    #       - httpd-tools
    #       - mariadb-server
    #       - mariadb
    #       - php
    #       - php-mysqlnd
