- name: Order Hosts Execution
  hosts: all
  gather_facts: false
  order: reverse_sorted
  serial: 1
  tasks:
  - name: Task 1
    ansible.builtin.command: sleep 1
  #- name: Task 2
  #  ansible.builtin.command: sleep 1
