---
# handlers file for security_server

- name: Security Package Installed
  ansible.builtin.debug:
    msg: "Security Package Installed"

- name: Restart Security Service
  ansible.builtin.service:
    name: "{{ security_server_service }}"
    state: restarted

- name: Security Port Opened
  ansible.builtin.debug:
    msg: "Security Port Opened for Public"
