download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/oracle-oci-4.40.0.tar.gz
format_version: 1.0.0
name: oci
namespace: oracle
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.40.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/oracle/oci/versions/4.40.0/
